<?php

/** Scoreboard — the workbook's Index sheet as a PHP page. */

declare(strict_types=1);

require_once __DIR__ . '/scoring.php';
require_once __DIR__ . '/ui.php';

$db = ise_db();
$board = iseLoadScoreboard($db);
$multiplier = $board['multiplier'];

$sets = [];
foreach ($board['conclusions'] as $id => $row) {
    $sets[$row['example_set'] ?? 'other'][] = $id;
}
foreach ($sets as &$ids) {
    usort($ids, fn ($a, $b) => ($board['scores'][$b] ?? 0) <=> ($board['scores'][$a] ?? 0));
}
unset($ids);

$setTitles = [
    'church' => 'From the original workbook (belief 46 and its sub-arguments)',
    'trees' => 'Synthetic example (exercises linkage scores)',
];

isePageOpen('Conclusion scores — Idea Stock Exchange demo');
?>
<h1>Every conclusion, ranked by its reasons</h1>
<p class="lede">
  This page is generated by PHP retrieving scores from SQL. The score of each
  conclusion is computed twice &mdash; once inside the database by a recursive
  CTE, once in PHP recursing over plain edge rows &mdash; and rendered only when
  the two agree.
</p>

<?php if ($board['verified']): ?>
<div class="panel ok">&#10003; SQL recursive CTE and PHP recursion agree on all
  <?= count($board['scores']) ?> scores at m = <?= e(iseFormatScore($multiplier)) ?>.</div>
<?php else: ?>
<div class="panel fail">&#10007; The SQL and PHP scoring paths disagree — refusing to
  render scores. Check the schema and scoring.php.</div>
<?php endif; ?>

<p class="switcher">
  Sub-argument multiplier:
  <a href="?m=0.7" class="<?= $multiplier == 0.7 ? 'active' : '' ?>">m = 0.7 (the workbook&rsquo;s Index!O1)</a>
  <a href="?m=1" class="<?= $multiplier == 1.0 ? 'active' : '' ?>">m = 1.0 (the live sheets)</a>
</p>

<?php iseFormulaPanel($multiplier); ?>

<?php foreach ($sets as $setName => $ids): ?>
<h2><?= e($setTitles[$setName] ?? ucfirst((string) $setName)) ?></h2>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Conclusion</th>
      <th class="num">Agree</th>
      <th class="num">Disagree</th>
      <th class="num">Score</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($ids as $id):
        if (!$board['verified']) { break; }
        $breakdown = $board['breakdowns'][$id] ?? null;
        $score = $board['scores'][$id] ?? 0.0;
    ?>
    <tr>
      <td class="muted"><?= e($id) ?></td>
      <td><a href="belief.php?id=<?= urlencode((string) $id) ?>&amp;m=<?= e(iseFormatScore($multiplier)) ?>">
        <?= e($board['conclusions'][$id]['statement']) ?></a></td>
      <td class="num side-agree"><?= (int) ($breakdown['agree_count'] ?? 0) ?></td>
      <td class="num side-disagree"><?= (int) ($breakdown['disagree_count'] ?? 0) ?></td>
      <td class="num"><span class="score-pill<?= $score < 0 ? ' negative' : '' ?>">
        <?= e(iseFormatScore($score)) ?></span></td>
    </tr>
    <?php endforeach; ?>
  </tbody>
</table>
<?php endforeach; ?>

<h2>How the retrieval works</h2>
<p>
  Scores are never stored — they are derived from the reason graph on every
  request, exactly as Excel recomputed the workbook on every edit. The single
  query below expands each path from a conclusion down through its reasons;
  a path through <em>k</em> edges contributes
  <code>m<sup>k&minus;1</sup> &middot; &Pi;&nbsp;linkage &middot; &Pi;&nbsp;sign</code>,
  and the sum of path weights per conclusion is its score.
</p>
<pre class="sql"><?= e(ISE_SCORE_SQL) ?></pre>
<?php
isePageClose();
